<%
distrib, infos    = ENV.fetch('DISTRIB', 'debian:stretch/9').split(':')
codename, version = infos.split('/')
%>
---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  formula: shorewall

  # Install Salt from official repositories
  salt_install: apt
  salt_version: latest
  salt_apt_repo: https://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64
  salt_apt_repo_key: https://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64/latest/SALTSTACK-GPG-KEY.pub

  # Don't install Chef
  require_chef: false

  # Configure Salt
  state_top:
    base:
      '*':
        - shorewall

  pillars:
    top.sls:
      base:
        '*':
          - shorewall
    shorewall.sls:
      shorewall:
        zones:
          net:
            type: ipv4
            interfaces:
              eth0:
                ipv: 4
                broadcast: detect
                options: dhcp,tcpflags,logmartians,nosmurfs

        policy:
          - source: $FW
            dest: net
            policy: ACCEPT
            comment: Allow Firewall to connect to World

          - source: net
            dest: $FW
            policy: ACCEPT
            comment: Allow World to connect to Firewall

        rules:
          ALL:
            - action: ACCEPT
              source: net
              dest: $FW
              comment: Allow World to connect to Firewall

            - action: ACCEPT
              source: $FW
              dest: net
              comment: Allow Firewall to connect to World

platforms:
  - name: <%= distrib %>-<%= codename %>
    driver_config:
      image: "<%= distrib %>:<%= codename %>"
      platform: <%= distrib %>
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
      <% if codename == 'wheezy' %>
      run_command: /sbin/init
      <% else %>
      run_command: /lib/systemd/systemd
      <% end %>

verifier:
  name: inspec
  reporter:
    - progress

suites:
  - name: shorewall
